from tortoise import fields
from tortoise.models import Model


class EventModel(Model):
    id = fields.IntField(pk=True)
    event_id = fields.CharField(16, index=True)
    day = fields.IntField()
    month = fields.IntField()
    year = fields.IntField()
    start = fields.CharField(8)
    country = fields.CharField(128)
    tournament = fields.CharField(128)
    tour = fields.CharField(128)
    team_1 = fields.CharField(128)
    team_2 = fields.CharField(128)
    team_1_coefficient = fields.FloatField()
    draw_coefficient = fields.FloatField()
    team_2_coefficient = fields.FloatField()
    team_1_goals = fields.IntField()
    team_2_goals = fields.IntField()
    team_1_voices = fields.IntField()
    draw_voices = fields.IntField()
    team_2_voices = fields.IntField()
    team_1_voices_percent = fields.FloatField()
    draw_voices_percent = fields.FloatField()
    team_2_voices_percent = fields.FloatField()


class Tennis(Model):
    id = fields.IntField(pk=True)
    event_id = fields.CharField(16, index=True)
    day = fields.IntField()
    month = fields.IntField()
    year = fields.IntField()
    start = fields.CharField(8)
    country = fields.CharField(128)
    tournament = fields.CharField(128)
    tour = fields.CharField(128)
    team_1 = fields.CharField(128)
    team_2 = fields.CharField(128)

    team_1_rank = fields.IntField(null=True)
    team_2_rank = fields.IntField(null=True)

    team_1_set_1 = fields.IntField(null=True)
    team_1_set_1_break = fields.IntField(null=True)
    team_1_set_2 = fields.IntField(null=True)
    team_1_set_2_break = fields.IntField(null=True)
    team_1_set_3 = fields.IntField(null=True)
    team_1_set_3_break = fields.IntField(null=True)
    team_1_set_4 = fields.IntField(null=True)
    team_1_set_4_break = fields.IntField(null=True)
    team_1_set_5 = fields.IntField(null=True)
    team_1_set_5_break = fields.IntField(null=True)

    team_2_set_1 = fields.IntField(null=True)
    team_2_set_1_break = fields.IntField(null=True)
    team_2_set_2 = fields.IntField(null=True)
    team_2_set_2_break = fields.IntField(null=True)
    team_2_set_3 = fields.IntField(null=True)
    team_2_set_3_break = fields.IntField(null=True)
    team_2_set_4 = fields.IntField(null=True)
    team_2_set_4_break = fields.IntField(null=True)
    team_2_set_5 = fields.IntField(null=True)
    team_2_set_5_break = fields.IntField(null=True)

    status = fields.CharField(128, null=True)
    time = fields.CharField(16, null=True)
    set_1_time = fields.CharField(16, null=True)
    set_2_time = fields.CharField(16, null=True)
    set_3_time = fields.CharField(16, null=True)
    set_4_time = fields.CharField(16, null=True)
    set_5_time = fields.CharField(16, null=True)

    team_1_coefficient = fields.FloatField()
    team_2_coefficient = fields.FloatField()
    team_1_goals = fields.IntField()
    team_2_goals = fields.IntField()
    team_1_voices = fields.IntField()
    team_2_voices = fields.IntField()
    team_1_voices_percent = fields.FloatField()
    team_2_voices_percent = fields.FloatField()

